--Oracle, por defecto diferencia entre may y min en sus textos (string/varchar)
--Todo lo que no sea un numero se escribe entre comillas simples '...' 
--Para filtrar se utiliza where  y se escribe solo una vez en toda la consulta despues del from
--MOSTRAR TODOS LOS EMPLEADOS DEL DEP 10
SELECT * FROM EMP where DEPT_NO=10;
--MOSTRAR TODOS LOS EEMPLEADOS CUYO OFICIO SEA DIRECTOR
SELECT * FROM EMP where OFICIO='DIRECTOR';
--MOSTRAR TODOS LOS EMP CUYO OFICIO SEA DIFERENTE A DIRECTOR
SELECT * FROM EMP WHERE OFICIO<>'DIRECTOR';
--TAMBIEN  FUNCIONA != PERO NO ES UN ESTÁNDAR Y HACE LO MISMO
SELECT * FROM EMP WHERE OFICIO!='DIRECTOR';
--Existen tambien operadores relacionales que permiten realizar mas de una pregunta dentro de una consulta
/*
OR --> MUESTRA LOS DATOS DE CADA FILTRO
AND --> TODOS LOS FILTROS DEBEN CUMPLIRSE
NOT -->  NEGACION DE UNA CONDICION (EIVTAR SIEMPRE)
*/
--MOSTRAR EMPLEADOS DEL DEP 10 Y QUE TENGA OFICIO DIRECTOR
SELECT * FROM EMP WHERE OFICIO='DIRECTOR' AND DEPT_NO=10;
--Si uso un OR 
SELECT * FROM EMP WHERE OFICIO='DIRECTOR' OR DEPT_NO=10;
--MOSTRAR LOS EMPLEADOS DEL  DEP 10 Y DEP 20
SELECT * FROM EMP WHERE DEPT_NO=20 AND DEPT_NO=10;
--ESTA COMBINACION NO TIENE SENTIDO 
SELECT * FROM EMP WHERE DEPT_NO=20 OR DEPT_NO=10;

--EXISTEN OTROS OPERADORES ADEMAS DE LOS ESTANDAR
--BETWEEN MUESTRA LOS DATOS ENTRE UN RANGO INCLUIDO
--MOSTRAR EMP CUYO SALARIO ESTE ENTRE 251000 Y 390000
SELECT * FROM EMP WHERE SALARIO BETWEEN 251000 AND 390000;
SELECT * FROM EMP WHERE SALARIO BETWEEN 251000 AND 390000 ORDER BY SALARIO;
--SE PUEDE HACER LA MISMA CONSULTA CON OPERADORES Y ES EFICIENTE
SELECT * FROM EMP WHERE SALARIO>=251000 AND SALARIO<= 390000 ORDER BY SALARIO;
--LA NEGACION ES ALGO DE LO QUE SE DEBE HUIR
--MOSTRAR LOS EMPLEADOS QUE NO SEAN DIRECTOR
SELECT * FROM EMP WHERE NOT OFICIO='DIRECTOR';
--PODEMOS REALIZAR LA CONSULTA CON OPERADOR
SELECT * FROM EMP WHERE OFICIO <>'DIRECTOR';
--EXISTE UN OPERADOR PARA BUSCAR COINCIDENCIAS EN TEXTOS (ESTANDAR)
--PERMITE MEDIANTE CARACTERES ESPECIALES HACER FILTROS EN TEXTOS 
/*
% BUSCA CUALQUIER CARACTER Y LONGITUD
_ CUALQUIER CARACTER
? UN CARACTER NUMERICO
*/
--MOSTRAR EMP CUYO APELLIDO COMIENZA EN s 
SELECT * FROM EMP WHERE APELLIDO LIKE 's%';
--MOSTRAR EMP CUYO APELLIDO COMIENZA EN s Y FINALIZA CON a
SELECT * FROM EMP WHERE APELLIDO LIKE 's%a';
--MOSTRAR TODOS LOS EMPLEADOS CUYO APELLIDO SEA DE 4 LETRAS
SELECT * FROM EMP WHERE APELLIDO LIKE '____';
--EXISTE OTRO OPERADOR PARA BUSCAR COINCIDENCIAS DE IGUALDAD EN UN MISMO CAMPO
--in (valor1, valor2)
--MOSTRAR LOS EMPLEADOS DEL DEP 10 Y DEP 20
SELECT * FROM EMP WHERE DEPT_NO=20 OR DEPT_NO=10;
--MOSTRAR LOS EMPLEADOS DEL DEP 10, 20 Y 30
SELECT * FROM EMP WHERE DEPT_NO=20 OR DEPT_NO=10 OR DEPT_NO=30;
SELECT * FROM EMP WHERE DEPT_NO IN (10,20,30,55,65,77);
--LAS CONSULTAS SON IGUAL DE EFICIENTES 
--TENEMOS EL OPERADOR NOT IN
--MOSTRAR TODOS LOS EMPLEADOS QUE NO ESTEN EN EL DEPARTAMENTO 10 Y 20
SELECT * FROM EMP WHERE NOT DEPT_NO IN (10,20); 
--ES UNA NEGACION DE UNA CONDICION Y HACE DOS CONSULTAS 
SELECT * FROM EMP WHERE DEPT_NO NOT IN (10,20); 
--CAMPOS CALCULADOS
--UN CAMPO CALCULADO ES UNA HERRAMIENTA EN UNA CONSULTA 
--SIRVE PARA GENERAR CAMPOS QUE NO EXSTAN EN LA TABLA Y SE PUEDEN CALCULAR
--MOSTRAR EL APELLIDO, EL SALARIO, COMISION Y SALARIO TOTAL DE EMP 

SELECT APELLIDO, SALARIO, COMISION, (SALARIO+COMISION) FROM EMP;
--SIEMPRE HAY QUE DAR UN ALIAS A LOS CAMPOS CALCULADOS, 
--NO SE PUEDEN REPETIR NOMBRES DE COLUMNAS:
SELECT APELLIDO, SALARIO, COMISION, (SALARIO+COMISION) AS TOTAL FROM EMP;
--UN CAMPO CALCULADO SOLO ES PARA EL CURSOR
--CUYO SALARIO SEA MAYOR DE 344500 --> NO SE PUEDE HACER
--WHERE SOLO BUSCA EN LA TABLA
SELECT APELLIDO, SALARIO, COMISION, (SALARIO+COMISION) AS TOTAL FROM EMP
WHERE (SALARIO + COMISION) >=  344500;
--QUEREMOS LA CONSULTA ORIGINAL Y ORDENAR POR ELLA
SELECT APELLIDO, SALARIO, COMISION, (SALARIO+COMISION) AS TOTAL FROM EMP
ORDER BY TOTAL;
--LA ORDENACION SIEMPRE AFECTA AL SELECT
--WHERE SE HACE SOBRE LOS DATOS DE LA TABLA

--CLAUSULA  DISTINCT: SE UTILIZA PARA EL SELECT,  ELIMINA REPETIDOS DE CONSULTA
--MOSTRAR OFICIO DE EMPLEADOS
SELECT DISTINCT OFICIO FROM EMP;
--MOSTRAR LOS DIFERENTES OFICIOS Y APELLIDOS DE LOS EMPLEADOS. 
SELECT DISTINCT OFICIO, APELLIDO FROM EMP;
--NO TIENE MUCHO SENTIDO PORQUE NO  TIENE NADA QUE VER
SELECT * FROM ENFERMO;
--MOSTRAR TODOS LOS ENFERMOS NACIDOS ANTES DEL 11/01/1970
SELECT APELLIDO, FECHA_NAC FROM  ENFERMO WHERE FECHA_NAC <'11/01/1970';
--MOSTRAR TODOS LOS ENFERMOS NACIDOS ANTES DEL 01/01/1970 
--ORDENADOS POR  NUMERO DE INSCRIPCION
SELECT INSCRIPCION, APELLIDO, FECHA_NAC FROM ENFERMO WHERE FECHA_NAC <'01/01/1970'
ORDER BY inscripcion;
--LISTADO TODOS LOS DATOS DE LA PLANTILLA DEL HOSPITAL DEL TURNO DE MAÑANA
SELECT * FROM plantilla;
SELECT * FROM plantilla where TURNO='M';
--LISTADO TODOS LOS DATOS DE LA PLANTILLA DEL HOSPITAL DEL TURNO DE NOCHE
SELECT * FROM plantilla where TURNO='N';
--LISTADO DE LOS DOCTORES CUYO SALARIO ANUAL SUPERE LOS 3.000.000€
SELECT * FROM doctor;
SELECT APELLIDO, SALARIO, (SALARIO*12) AS SALARIO_ANUAL FROM DOCTOR 
WHERE (SALARIO*12)>3000000;
--VISUALIZAR EMPLEADOS DE PLANTILLA DE T/M 
--QUE TENGAN SALARIO ENTRE 2000000 Y 2250000
SELECT APELLIDO,TURNO, SALARIO, (SALARIO*12) AS SALARIO_ANUAL FROM PLANTILLA 
WHERE turno='M' AND (SALARIO*12) BETWEEN 2000000 AND 2250000;

--VISUALIZAR EMP QUE  NO SE DIERON DE ALTA ENTRE 01/01/1980 Y 12/12/1982
SELECT * FROM emp;
SELECT APELLIDO, OFICIO, FECHA_ALT FROM EMP WHERE 
OFICIO='EMPLEADO' AND fecha_alt NOT IN ('01/01/80','12/12/82');
--MOSTRAR LOS NOMBRES DE LOS DEPARTAMENTOS SITUADOS EN MADRID O EN BARCELONA
SELECT  * FROM dept;
SELECT DNOMBRE, LOC FROM dept WHERE LOC='MADRID' OR LOC='BARCELONA';
desc ENFERMO;



